import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

function source(filePath: string) {
  return readFileSync(resolve(process.cwd(), filePath), 'utf8')
}

describe('Shared contacts guardrails', () => {
  it('keeps connection notifications wired into the app shell', () => {
    const app = source('src/App.tsx')

    expect(app).toContain("import { getUserConnections } from './lib/connections'")
    expect(app).toContain('summarizeConnectionNotifications')
    expect(app).toContain('readConnectionNotificationState')
    expect(app).toContain('writeConnectionNotificationState')
    expect(app).toContain('window.setInterval(refresh, 15000)')
    expect(app).toContain('window.addEventListener(CONNECTIONS_CHANGED_EVENT, refresh)')
    expect(app).toContain('document.addEventListener(\'visibilitychange\', handleVisibilityChange)')
    expect(app).toContain('sharedContactsBadgeCount={sharedContactsBadge.count}')
    expect(app).toContain('<Route path="shared" element={<Navigate to="/approvals" replace />} />')
  })

  it('keeps Shared contacts refreshing when users invite, accept, decline, or remove connections', () => {
    const approvalsPage = source('src/components/approvals/ApprovalsPage.tsx')

    expect(approvalsPage).toContain("import { CONNECTIONS_CHANGED_EVENT } from '@/lib/connectionNotifications'")
    expect(approvalsPage).toContain('const intervalId = window.setInterval(() => {')
    expect(approvalsPage).toContain('const nextConnections = await getUserConnections()')
    expect(approvalsPage).toContain('await createUserConnectionRequest(email)')
    expect(approvalsPage).toContain('await respondUserConnection(connection.id, status)')
    expect(approvalsPage.match(/window\.dispatchEvent\(new Event\(CONNECTIONS_CHANGED_EVENT\)\)/g)?.length).toBeGreaterThanOrEqual(2)
  })

  it('keeps the Shared contacts sidebar badge visible and accessible', () => {
    const sidebar = source('src/components/nav/Sidebar.tsx')

    expect(sidebar).toContain('sharedContactsBadgeCount?: number')
    expect(sidebar).toContain('sharedContactsBadgeLabel?: string')
    expect(sidebar).toContain('badgeCount={sharedContactsBadgeCount}')
    expect(sidebar).toContain('aria-label={badgeLabel ? `${label}: ${badgeLabel}` : label}')
    expect(sidebar).toContain("{badgeCount > 99 ? '99+' : badgeCount}")
  })

  it('keeps trusted-user RPC contracts intact', () => {
    const connections = source('src/lib/connections.ts')

    expect(connections).toContain("db.rpc('get_user_connections')")
    expect(connections).toContain("db.rpc('create_user_connection_request', { target_email: targetEmail })")
    expect(connections).toContain("db.rpc('respond_user_connection'")
    expect(connections).toContain('connection_id: connectionId')
    expect(connections).toContain('next_status: status')
    expect(connections).toContain("db.rpc('find_app_users_for_contact_emails', { contact_emails: contactEmails })")
  })

  it('keeps Share contacts searchable and visually scoped to selected fields', () => {
    const approvalsPage = source('src/components/approvals/ApprovalsPage.tsx')
    const collaboration = source('src/lib/collaboration.ts')
    const visibleFields = source('src/lib/sharedContactVisibleFields.ts')
    const contactDetail = source('src/components/contacts/ContactDetail.tsx')

    expect(approvalsPage).toContain('const [resourceSearch, setResourceSearch] = useState')
    expect(approvalsPage).toContain('placeholder="Search contacts, pods, sub-pods, companies, or campaigns"')
    expect(approvalsPage).toContain('SHARED_CONTACT_VISIBLE_FIELD_GROUPS.map')
    expect(approvalsPage).toContain('deriveSharedContactFieldScopes(selectedVisibleFieldIds)')
    expect(approvalsPage).toContain('visible_field_ids: selectedVisibleFieldIds')
    expect(collaboration).toContain('encodeSharedContactFieldScopes(visible_field_ids)')
    expect(collaboration).toContain('decodeSharedContactVisibleFieldIdsFromScopes(rawFieldScopes)')
    expect(collaboration).toContain('field_scopes: normalizeSharedContactFieldScopes(rawFieldScopes)')
    expect(visibleFields).toContain('export const SHARED_CONTACT_VISIBLE_FIELD_GROUPS')
    expect(visibleFields).toContain("const VISIBLE_FIELD_TOKEN_PREFIX = 'visible:'")
    expect(visibleFields).toContain('encodeSharedContactVisibleFieldToken')
    expect(visibleFields).toContain('decodeSharedContactVisibleFieldIdsFromScopes')
    expect(visibleFields).toContain("scope: 'public_profile'")
    expect(visibleFields).toContain("scope: 'private_contact'")
    expect(visibleFields).toContain("scope: 'relationship_private'")
    expect(visibleFields).toContain("scope: 'investment_private'")
    expect(visibleFields).toContain("scope: 'campaign_private'")
    expect(contactDetail).toContain('visibleFieldIds?: readonly string[]')
    expect(contactDetail).toContain('sharedVisibleFieldForKey')
    expect(contactDetail).toContain('SHARED_FIELD_VISIBLE_REQUIREMENTS')
  })

  it('keeps incoming shared-contact requests visible and actionable for recipients', () => {
    const approvalsPage = source('src/components/approvals/ApprovalsPage.tsx')
    const collaboration = source('src/lib/collaboration.ts')
    const migration = source('supabase/migrations/20260701142000_incoming_shared_contact_requests.sql')
    const responseFixMigration = source('supabase/migrations/20260702033000_fix_shared_request_response_rpc.sql')

    expect(collaboration).toContain("db.rpc('get_incoming_collaboration_access_grants')")
    expect(collaboration).toContain("db.rpc('respond_incoming_collaboration_access_grant'")
    expect(collaboration).toContain("db.rpc('get_shared_contacts_with_me')")
    expect(approvalsPage).toContain("type ApprovalTab = 'requests' | 'proposals' | 'shared_requests'")
    expect(approvalsPage).toContain('label="Shared requests"')
    expect(approvalsPage).toContain('busyRequestId={busySharedRequestId}')
    expect(approvalsPage).toContain('highlightedRequestId={highlightedSharedRequestId}')
    expect(approvalsPage).toContain('<SharedRequestFeedbackBanner key={sharedRequestFeedback.id} feedback={sharedRequestFeedback} />')
    expect(approvalsPage).toContain('setSearchText(grant.resource_label)')
    expect(approvalsPage).toContain("sharedContactManagerRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })")
    expect(approvalsPage).toContain('status: shareByEmail ? \'pending\' : \'accepted\'')
    expect(approvalsPage).toContain('subject_email: shareByEmail ? normalizedRecipientEmail : null')
    expect(migration).toContain('CREATE OR REPLACE FUNCTION public.get_incoming_collaboration_access_grants()')
    expect(migration).toContain('CREATE OR REPLACE FUNCTION public.respond_incoming_collaboration_access_grant')
    expect(migration).toContain('CREATE OR REPLACE FUNCTION public.get_shared_contacts_with_me()')
    expect(migration).toContain('contacts.pod_ids::text[]')
    expect(migration).toContain('contacts.category_ids::text[]')
    expect(migration).toContain('contacts.company_ids::text[]')
    expect(migration).toContain('shared_contacts.pod_ids::text[]')
    expect(migration).toContain('shared_contacts.category_ids::text[]')
    expect(migration).toContain('shared_contacts.company_ids::text[]')
    expect(migration).toContain(') || jsonb_build_object(')
    expect(responseFixMigration).toContain('CREATE OR REPLACE FUNCTION public.respond_incoming_collaboration_access_grant')
    expect(responseFixMigration).toContain('target_grant.subject_id')
    expect(responseFixMigration).toContain('target_grant.subject_email')
    expect(responseFixMigration).toContain('target_grant.subject_label')
    expect(responseFixMigration).toContain('WHERE grants.id = target_grant.id')
    expect(responseFixMigration).toContain('GRANT EXECUTE ON FUNCTION public.respond_incoming_collaboration_access_grant(uuid, text) TO authenticated')
  })

  it('keeps accepted shared contacts openable as scoped contact cards', () => {
    const approvalsPage = source('src/components/approvals/ApprovalsPage.tsx')
    const recordsList = source('src/components/records/RecordsList.tsx')
    const contactDetail = source('src/components/contacts/ContactDetail.tsx')

    expect(recordsList).toContain('getSharedContactsWithMe')
    expect(recordsList).toContain('const [incomingSharedContacts, setIncomingSharedContacts]')
    expect(recordsList).toContain("relationshipScope === 'shared_with_me' ? sharedWithMeContacts : contacts")
    expect(recordsList).toContain('const isIncomingSharedContact = incomingSharedContacts.some')
    expect(recordsList).toContain('setIncomingSharedContacts(prev => prev.map(snapshot => (')
    expect(recordsList).toContain('snapshot.contact.id === updated.id')
    expect(recordsList).toContain('contact: normalizedUpdated')
    expect(recordsList).toContain('sharedAccess={selectedContactShareAccess}')
    expect(approvalsPage).toContain('const [selectedSharedContact, setSelectedSharedContact]')
    expect(approvalsPage).toContain('onOpenContact={handleOpenSharedContact}')
    expect(approvalsPage).toContain('sharedAccess={selectedSharedContact.shareAccess}')
    expect(approvalsPage).toContain('Shared with me')
    expect(approvalsPage).toContain('Shared by me')
    expect(contactDetail).toContain('export type ContactDetailShareAccess')
    expect(contactDetail).toContain('contactCardReadOnly')
    expect(contactDetail).toContain('scopeAllowsSharedField')
    expect(contactDetail).toContain('sharedVisibleFieldForKey')
    expect(recordsList).toContain('visibleFieldIds: snapshot.visible_field_ids')
    expect(approvalsPage).toContain('visibleFieldIds: snapshot.visible_field_ids')
    expect(contactDetail).toContain('if (isInboundSharedContact && sectionId === \'recent_activity\') return false')
  })

  it('keeps Editor and Admin shared contacts editable through a guarded RPC', () => {
    const collaboration = source('src/lib/collaboration.ts')
    const contactDetail = source('src/components/contacts/ContactDetail.tsx')
    const approvalsPage = source('src/components/approvals/ApprovalsPage.tsx')
    const recordsList = source('src/components/records/RecordsList.tsx')
    const migration = source('supabase/migrations/20260702143000_shared_contact_editor_permissions.sql')
    const saveStabilityMigration = source('supabase/migrations/20260702170000_stabilize_shared_contact_save.sql')

    expect(collaboration).toContain("db.rpc('update_shared_contact_with_grant'")
    expect(contactDetail).toContain("sharedAccess?.permissionLevel === 'edit' || sharedAccess?.permissionLevel === 'admin'")
    expect(contactDetail).toContain('updateSharedContactWithGrant(sharedAccess.grantId')
    expect(contactDetail).toContain('sharedWritablePatch')
    expect(contactDetail).toContain('dirtySharedWritablePatch')
    expect(contactDetail).toContain('stableComparableValue')
    expect(contactDetail).toContain('contactCardStructureReadOnly')
    expect(approvalsPage).toContain('grantId: snapshot.grant_id')
    expect(recordsList).toContain('grantId: meta.grantId')
    expect(migration).toContain("grants.permission_level IN ('edit', 'admin')")
    expect(migration).toContain('Shared contact field is not visible for editing')
    expect(migration).toContain('GRANT EXECUTE ON FUNCTION public.update_shared_contact_with_grant(uuid, uuid, jsonb) TO authenticated')
    expect(saveStabilityMigration).toContain("grants.permission_level IN ('edit', 'admin')")
    expect(saveStabilityMigration).toContain('Shared contact field is not visible for editing')
    expect(saveStabilityMigration).toContain('RETURN scoped_contact')
    expect(saveStabilityMigration).toContain("birthday = CASE WHEN _contact_patch ? 'birthday' THEN nullif(_contact_patch ->> 'birthday', '') ELSE contacts.birthday END")
    expect(saveStabilityMigration).not.toContain("birthday = CASE WHEN _contact_patch ? 'birthday' THEN nullif(_contact_patch ->> 'birthday', '')::date")
    expect(saveStabilityMigration).toContain("cadence_override = CASE WHEN _contact_patch ? 'cadence_override' THEN nullif(_contact_patch ->> 'cadence_override', '')::public.cadence ELSE contacts.cadence_override END")
    expect(saveStabilityMigration).toContain("global_region = CASE WHEN _contact_patch ? 'global_region' THEN nullif(_contact_patch ->> 'global_region', '')::public.global_region ELSE contacts.global_region END")
    expect(saveStabilityMigration).toContain("gender = CASE WHEN _contact_patch ? 'gender' THEN nullif(_contact_patch ->> 'gender', '')::public.gender_type ELSE contacts.gender END")
    expect(saveStabilityMigration).toContain("contact_frequency = CASE WHEN _contact_patch ? 'contact_frequency' THEN nullif(_contact_patch ->> 'contact_frequency', '')::public.contact_frequency ELSE contacts.contact_frequency END")
    expect(saveStabilityMigration).toContain("type = CASE WHEN _contact_patch ? 'type' THEN coalesce(nullif(_contact_patch ->> 'type', '')::public.relationship_type, contacts.type) ELSE contacts.type END")
    expect(saveStabilityMigration).toContain("status = CASE WHEN _contact_patch ? 'status' THEN coalesce(nullif(_contact_patch ->> 'status', '')::public.relationship_status, contacts.status) ELSE contacts.status END")
    expect(saveStabilityMigration).not.toContain('FROM public.get_shared_contacts_with_me() AS incoming')
  })
})
