import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

function source(filePath: string) {
  return readFileSync(resolve(process.cwd(), filePath), 'utf8')
}

describe('Shared contacts guardrails', () => {
  it('keeps connection notifications wired into the app shell', () => {
    const app = source('src/App.tsx')

    expect(app).toContain("import { getUserConnections } from './lib/connections'")
    expect(app).toContain('summarizeConnectionNotifications')
    expect(app).toContain('readConnectionNotificationState')
    expect(app).toContain('writeConnectionNotificationState')
    expect(app).toContain('window.setInterval(refresh, 15000)')
    expect(app).toContain('window.addEventListener(CONNECTIONS_CHANGED_EVENT, refresh)')
    expect(app).toContain('document.addEventListener(\'visibilitychange\', handleVisibilityChange)')
    expect(app).toContain('sharedContactsBadgeCount={sharedContactsBadge.count}')
    expect(app).toContain('<Route path="shared" element={<Navigate to="/approvals" replace />} />')
  })

  it('keeps Shared contacts refreshing when users invite, accept, decline, or remove connections', () => {
    const approvalsPage = source('src/components/approvals/ApprovalsPage.tsx')

    expect(approvalsPage).toContain("import { CONNECTIONS_CHANGED_EVENT } from '@/lib/connectionNotifications'")
    expect(approvalsPage).toContain('const intervalId = window.setInterval(() => {')
    expect(approvalsPage).toContain('getIncomingCollaborationAccessGrants()')
    expect(approvalsPage).toContain('getSharedContactsWithMe()')
    expect(approvalsPage).toContain('setIncomingGrants(nextIncomingGrants)')
    expect(approvalsPage).toContain('setIncomingSharedContacts(nextIncomingSharedContacts)')
    expect(approvalsPage).toContain('Failed to refresh shared contact requests')
    expect(approvalsPage).toContain('await createUserConnectionRequest(email)')
    expect(approvalsPage).toContain('await respondUserConnection(connection.id, status)')
    expect(approvalsPage.match(/window\.dispatchEvent\(new Event\(CONNECTIONS_CHANGED_EVENT\)\)/g)?.length).toBeGreaterThanOrEqual(2)
  })

  it('keeps Shared contacts accessible from Relationships instead of the sidebar', () => {
    const sidebar = source('src/components/nav/Sidebar.tsx')
    const recordsList = source('src/components/records/RecordsList.tsx')

    expect(sidebar).toContain('sharedContactsBadgeCount?: number')
    expect(sidebar).toContain('sharedContactsBadgeLabel?: string')
    expect(sidebar).not.toContain('label="Shared contacts"')
    expect(recordsList).toContain('Shared contacts Detail view')
    expect(recordsList).toContain("navigate('/approvals')")
    expect(recordsList).toContain('Share current selection')
    expect(recordsList).toContain('visibleFieldIds={selectedShareVisibleFieldIds}')
    expect(recordsList).toContain('visibleFieldLabels={selectedShareVisibleFieldLabels}')
    expect(recordsList).toContain('Choose at least one shareable visible section before sharing.')
    expect(sidebar).toContain('aria-label={badgeLabel ? `${label}: ${badgeLabel}` : label}')
    expect(sidebar).toContain("{badgeCount > 99 ? '99+' : badgeCount}")
  })

  it('keeps quick shared-contact selection scoped to visible sections', () => {
    const modal = source('src/components/collaboration/CollaborationQuickAccessModal.tsx')
    const recordsList = source('src/components/records/RecordsList.tsx')

    expect(recordsList).toContain('function sharedContactVisibleFieldForColumn')
    expect(recordsList).toContain("Pods: 'pods'")
    expect(recordsList).toContain("'Sub-pods': 'sub_pods'")
    expect(recordsList).toContain("Campaigns: 'campaign'")
    expect(recordsList).toContain("if (/^Pod \\d+$/.test(normalized)) return 'pods'")
    expect(recordsList).toContain("if (/^Sub-pod \\d+$/.test(normalized)) return 'sub_pods'")
    expect(recordsList).toContain("if (/^Campaign \\d+$/.test(normalized)) return 'campaign'")
    expect(recordsList).toContain('variant="selection"')
    expect(recordsList).toContain("import { getUserConnections, type UserConnection } from '@/lib/connections'")
    expect(recordsList).toContain('function mergeShareAccessMembers(workspaceMembers: WorkspaceMember[], connections: UserConnection[])')
    expect(recordsList).toContain(".filter(connection => connection.status === 'accepted')")
    expect(recordsList).toContain('getUserConnections()')
    expect(recordsList).toContain('setWorkspaceMembers(mergeShareAccessMembers(members, connections))')
    expect(modal).toContain("type QuickAccessVariant = 'full' | 'selection'")
    expect(modal).toContain('for (const resource of resources)')
    expect(modal).toContain("subject_email: subjectType === 'user' ? selectedMember?.email ?? null : null")
    expect(modal).toContain('visible_field_ids: isSelectionVariant ? visibleFieldIds : undefined')
    expect(modal).toContain('Reader')
    expect(modal).toContain('Editor')
    expect(modal).toContain('Require approval before editor changes apply')
  })

  it('keeps trusted-user RPC contracts intact', () => {
    const connections = source('src/lib/connections.ts')

    expect(connections).toContain("db.rpc('get_user_connections')")
    expect(connections).toContain("db.rpc('create_user_connection_request', { target_email: targetEmail })")
    expect(connections).toContain("db.rpc('respond_user_connection'")
    expect(connections).toContain('connection_id: connectionId')
    expect(connections).toContain('next_status: status')
    expect(connections).toContain("db.rpc('find_app_users_for_contact_emails', { contact_emails: contactEmails })")
  })

  it('keeps Share contacts searchable and visually scoped to selected fields', () => {
    const approvalsPage = source('src/components/approvals/ApprovalsPage.tsx')
    const collaboration = source('src/lib/collaboration.ts')
    const visibleFields = source('src/lib/sharedContactVisibleFields.ts')
    const contactDetail = source('src/components/contacts/ContactDetail.tsx')

    expect(approvalsPage).toContain('const [resourceSearch, setResourceSearch] = useState')
    expect(approvalsPage).toContain('placeholder="Search contacts, pods, sub-pods, companies, or campaigns"')
    expect(approvalsPage).toContain('function shareUserOptionLabel')
    expect(approvalsPage).toContain('Connection')
    expect(approvalsPage).toContain('Request target:')
    expect(approvalsPage).toContain("source: 'connection'")
    expect(approvalsPage).not.toContain('fetchWorkspaceMembers')
    expect(approvalsPage).toContain('SHARED_CONTACT_VISIBLE_FIELD_GROUPS.map')
    expect(approvalsPage).toContain('deriveSharedContactFieldScopes(selectedVisibleFieldIds)')
    expect(approvalsPage).toContain('visible_field_ids: selectedVisibleFieldIds')
    expect(approvalsPage).toContain('selectedVisibleFieldCount > 0')
    expect(approvalsPage).not.toContain('disabled={locked}')
    expect(collaboration).toContain('encodeSharedContactFieldScopes(visible_field_ids)')
    expect(collaboration).toContain('export async function updateCollaborationAccessGrant')
    expect(collaboration).toContain("event_type: 'access_grant_updated'")
    expect(collaboration).toContain('decodeSharedContactVisibleFieldIdsFromScopes(rawFieldScopes)')
    expect(collaboration).toContain('field_scopes: normalizeSharedContactFieldScopes(rawFieldScopes)')
    expect(visibleFields).toContain('export const SHARED_CONTACT_VISIBLE_FIELD_GROUPS')
    expect(visibleFields).toContain('export const DEFAULT_SHARED_CONTACT_VISIBLE_FIELD_IDS: SharedContactVisibleFieldId[] = []')
    expect(visibleFields).not.toContain('required: true')
    expect(visibleFields).toContain("const VISIBLE_FIELD_TOKEN_PREFIX = 'visible:'")
    expect(visibleFields).toContain('encodeSharedContactVisibleFieldToken')
    expect(visibleFields).toContain('decodeSharedContactVisibleFieldIdsFromScopes')
    expect(visibleFields).toContain("scope: 'public_profile'")
    expect(visibleFields).toContain("scope: 'private_contact'")
    expect(visibleFields).toContain("scope: 'relationship_private'")
    expect(visibleFields).toContain("scope: 'investment_private'")
    expect(visibleFields).toContain("scope: 'campaign_private'")
    expect(contactDetail).toContain('visibleFieldIds?: readonly string[]')
    expect(contactDetail).toContain('sharedVisibleFieldForKey')
    expect(contactDetail).toContain('SHARED_FIELD_VISIBLE_REQUIREMENTS')
  })

  it('keeps existing shared-by-me access editable without changing received shares', () => {
    const approvalsPage = source('src/components/approvals/ApprovalsPage.tsx')

    expect(approvalsPage).toContain('updateCollaborationAccessGrant')
    expect(approvalsPage).toContain('const [editingGrant, setEditingGrant] = useState<CollaborationAccessGrant | null>(null)')
    expect(approvalsPage).toContain('function handleEditSharedRow(row: SharedContactRow)')
    expect(approvalsPage).toContain("row.revokeKind !== 'grant'")
    expect(approvalsPage).toContain('onEditAccess={handleEditSharedRow}')
    expect(approvalsPage).toContain('<EditSharedAccessModal')
    expect(approvalsPage).toContain('title="Edit shared access"')
    expect(approvalsPage).toContain('submitLabel={saving ? \'Saving...\' : \'Save\'}')
    expect(approvalsPage).toContain('visible_field_ids: selectedVisibleFieldIds')
    expect(approvalsPage).toContain('if (canEditAccess) {')
    expect(approvalsPage).toContain('onOpenContact(row)')
  })

  it('keeps incoming shared-contact requests visible and actionable for recipients', () => {
    const approvalsPage = source('src/components/approvals/ApprovalsPage.tsx')
    const collaboration = source('src/lib/collaboration.ts')
    const migration = source('supabase/migrations/20260701142000_incoming_shared_contact_requests.sql')
    const responseFixMigration = source('supabase/migrations/20260702033000_fix_shared_request_response_rpc.sql')

    expect(collaboration).toContain("db.rpc('get_incoming_collaboration_access_grants')")
    expect(collaboration).toContain("db.rpc('respond_incoming_collaboration_access_grant'")
    expect(collaboration).toContain("db.rpc('get_shared_contacts_with_me')")
    expect(approvalsPage).toContain("type SharedStatusFilter = 'all' | 'pending' | 'accepted' | 'removed'")
    expect(approvalsPage).toContain('const STATUS_OPTIONS')
    expect(approvalsPage).toContain("{ value: 'pending', label: 'Pending' }")
    expect(approvalsPage).toContain("{ value: 'accepted', label: 'Accepted' }")
    expect(approvalsPage).toContain("{ value: 'removed', label: 'Removed' }")
    expect(approvalsPage).toContain('statusFilter={statusFilter}')
    expect(approvalsPage).toContain('onStatusFilterChange={setStatusFilter}')
    expect(approvalsPage).toContain('busyRequestId={busySharedRequestId}')
    expect(approvalsPage).toContain('highlightedRequestId={highlightedSharedRequestId}')
    expect(approvalsPage).toContain('onRespondSharedRequest={handleRespondSharedRequest}')
    expect(approvalsPage).toContain("approveLabel=\"Accept\"")
    expect(approvalsPage).toContain("rejectLabel=\"Remove\"")
    expect(approvalsPage).toContain('<SharedRequestFeedbackBanner key={sharedRequestFeedback.id} feedback={sharedRequestFeedback} />')
    expect(approvalsPage).toContain('setSearchText(grant.resource_label)')
    expect(approvalsPage).toContain("setStatusFilter('accepted')")
    expect(approvalsPage).toContain("setStatusFilter('removed')")
    expect(approvalsPage).toContain("sharedContactManagerRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })")
    expect(approvalsPage).not.toContain('function SharedRequestsTable')
    expect(approvalsPage).toContain('status: shareByEmail ? \'pending\' : \'accepted\'')
    expect(approvalsPage).toContain('subject_email: shareByEmail ? normalizedRecipientEmail : null')
    expect(migration).toContain('CREATE OR REPLACE FUNCTION public.get_incoming_collaboration_access_grants()')
    expect(migration).toContain('CREATE OR REPLACE FUNCTION public.respond_incoming_collaboration_access_grant')
    expect(migration).toContain('CREATE OR REPLACE FUNCTION public.get_shared_contacts_with_me()')
    expect(migration).toContain('contacts.pod_ids::text[]')
    expect(migration).toContain('contacts.category_ids::text[]')
    expect(migration).toContain('contacts.company_ids::text[]')
    expect(migration).toContain('shared_contacts.pod_ids::text[]')
    expect(migration).toContain('shared_contacts.category_ids::text[]')
    expect(migration).toContain('shared_contacts.company_ids::text[]')
    expect(migration).toContain(') || jsonb_build_object(')
    expect(responseFixMigration).toContain('CREATE OR REPLACE FUNCTION public.respond_incoming_collaboration_access_grant')
    expect(responseFixMigration).toContain('target_grant.subject_id')
    expect(responseFixMigration).toContain('target_grant.subject_email')
    expect(responseFixMigration).toContain('target_grant.subject_label')
    expect(responseFixMigration).toContain('WHERE grants.id = target_grant.id')
    expect(responseFixMigration).toContain('GRANT EXECUTE ON FUNCTION public.respond_incoming_collaboration_access_grant(uuid, text) TO authenticated')
  })

  it('keeps Shared contact manager delete actions from removing original contacts', () => {
    const approvalsPage = source('src/components/approvals/ApprovalsPage.tsx')
    const collaboration = source('src/lib/collaboration.ts')
    const accessGrantApi = source('api/collaboration/access-grant.ts')
    const migration = source('supabase/migrations/20260706143000_shared_contact_manager_row_actions.sql')

    expect(approvalsPage).toContain('selectedSharedRowIds')
    expect(approvalsPage).toContain('busySharedRowIds')
    expect(approvalsPage).toContain('uniqueSharedActionRows(rows)')
    expect(approvalsPage).toContain('Remove selected')
    expect(approvalsPage).toContain('Delete selected')
    expect(approvalsPage).toContain('Select all shared contacts')
    expect(approvalsPage).toContain('Select ${row.contactName}')
    expect(approvalsPage).toContain('Delete from shared contact history')
    expect(approvalsPage).toContain("await runSharedRowsAction([row], 'remove')")
    expect(approvalsPage).toContain("await runSharedRowsAction([row], 'delete')")
    expect(approvalsPage).toContain('await removeSharedRowAccess(row)')
    expect(approvalsPage).toContain('await deleteSharedRowHistory(row)')
    expect(approvalsPage).toContain('await deleteCollaborationAccessGrant(row.revokeId)')
    expect(collaboration).toContain("db.rpc('remove_collaboration_access_grant'")
    expect(collaboration).toContain("authorizedCollaborationApi<{ grant: CollaborationAccessGrant }>('/api/collaboration/access-grant'")
    expect(accessGrantApi).toContain("from('collaboration_access_grants')")
    expect(accessGrantApi).toContain('.delete()')
    expect(accessGrantApi).toContain("from('workspace_members')")
    expect(accessGrantApi).not.toContain("from('contacts')")
    expect(collaboration).toContain('.is(\'dismissed_at\', null)')
    expect(migration).toContain('ADD COLUMN IF NOT EXISTS dismissed_at')
    expect(migration).toContain('CREATE OR REPLACE FUNCTION public.remove_collaboration_access_grant')
    expect(migration).toContain('CREATE OR REPLACE FUNCTION public.dismiss_collaboration_access_grant')
    expect(migration).toContain('revoked_at = coalesce(grants.revoked_at, now())')
    expect(migration).toContain('dismissed_at = coalesce(grants.dismissed_at, now())')
    expect(migration).toContain('GRANT EXECUTE ON FUNCTION public.remove_collaboration_access_grant(uuid) TO authenticated')
    expect(migration).toContain('GRANT EXECUTE ON FUNCTION public.dismiss_collaboration_access_grant(uuid) TO authenticated')
  })

  it('keeps accepted shared contacts openable as scoped contact cards', () => {
    const approvalsPage = source('src/components/approvals/ApprovalsPage.tsx')
    const recordsList = source('src/components/records/RecordsList.tsx')
    const contactDetail = source('src/components/contacts/ContactDetail.tsx')

    expect(recordsList).toContain('getSharedContactsWithMe')
    expect(recordsList).toContain('const [incomingSharedContacts, setIncomingSharedContacts]')
    expect(recordsList).toContain('organizeSharedContactsForWorkspace')
    expect(recordsList).toContain('const visibleRelationshipContacts = useMemo')
    expect(recordsList).toContain("relationshipScope === 'shared_with_me' ? sharedWithMeContacts : relationshipContacts")
    expect(recordsList).toContain('let result = visibleRelationshipContacts.filter')
    expect(recordsList).toContain('visibleRelationshipContacts.length === 0 ?')
    expect(recordsList).not.toContain('contacts.length === 0 ?')
    expect(recordsList).toContain('const isIncomingSharedContact = incomingSharedContacts.some')
    expect(recordsList).toContain('setIncomingSharedContacts(prev => prev.map(snapshot => (')
    expect(recordsList).toContain('snapshot.contact.id === updated.id')
    expect(recordsList).toContain('contact: normalizedUpdated')
    expect(recordsList).toContain('sharedAccess={selectedContactShareAccess}')
    expect(approvalsPage).toContain('const [selectedSharedContact, setSelectedSharedContact]')
    expect(approvalsPage).toContain('onOpenContact={handleOpenSharedContact}')
    expect(approvalsPage).toContain('sharedAccess={selectedSharedContact.shareAccess}')
    expect(approvalsPage).toContain('Shared with me')
    expect(approvalsPage).toContain('Shared by me')
    expect(contactDetail).toContain('export type ContactDetailShareAccess')
    expect(contactDetail).toContain('contactCardReadOnly')
    expect(contactDetail).toContain('scopeAllowsSharedField')
    expect(contactDetail).toContain('sharedVisibleFieldForKey')
    expect(recordsList).toContain('visibleFieldIds: snapshot.visible_field_ids')
    expect(approvalsPage).toContain('visibleFieldIds: snapshot.visible_field_ids')
    expect(contactDetail).toContain('if (isInboundSharedContact && sectionId === \'recent_activity\') return false')
  })

  it('allows shared-with-me contacts to be selected in relationships bulk selection', () => {
    const recordsList = source('src/components/records/RecordsList.tsx')

    expect(recordsList).toContain('const canSelectContact = useCallback((_contact: Contact) => true, [])')
    expect(recordsList).toContain("aria-label={allSelected ? 'Deselect all people' : 'Select all people'}")
    expect(recordsList).not.toContain('Reader shared contacts cannot be used for bulk actions')
  })

  it('keeps Editor and Admin shared contacts editable through a guarded RPC', () => {
    const collaboration = source('src/lib/collaboration.ts')
    const contactDetail = source('src/components/contacts/ContactDetail.tsx')
    const approvalsPage = source('src/components/approvals/ApprovalsPage.tsx')
    const recordsList = source('src/components/records/RecordsList.tsx')
    const migration = source('supabase/migrations/20260702143000_shared_contact_editor_permissions.sql')
    const saveStabilityMigration = source('supabase/migrations/20260702170000_stabilize_shared_contact_save.sql')

    expect(collaboration).toContain("db.rpc('update_shared_contact_with_grant'")
    expect(contactDetail).toContain("sharedAccess?.permissionLevel === 'edit' || sharedAccess?.permissionLevel === 'admin'")
    expect(contactDetail).toContain('updateSharedContactWithGrant(sharedAccess.grantId')
    expect(contactDetail).toContain('sharedWritablePatch')
    expect(contactDetail).toContain('dirtySharedWritablePatch')
    expect(contactDetail).toContain('stableComparableValue')
    expect(contactDetail).toContain('contactCardStructureReadOnly')
    expect(approvalsPage).toContain('grantId: snapshot.grant_id')
    expect(recordsList).toContain('grantId: meta.grantId')
    expect(migration).toContain("grants.permission_level IN ('edit', 'admin')")
    expect(migration).toContain('Shared contact field is not visible for editing')
    expect(migration).toContain('GRANT EXECUTE ON FUNCTION public.update_shared_contact_with_grant(uuid, uuid, jsonb) TO authenticated')
    expect(saveStabilityMigration).toContain("grants.permission_level IN ('edit', 'admin')")
    expect(saveStabilityMigration).toContain('Shared contact field is not visible for editing')
    expect(saveStabilityMigration).toContain('RETURN scoped_contact')
    expect(saveStabilityMigration).toContain("birthday = CASE WHEN _contact_patch ? 'birthday' THEN nullif(_contact_patch ->> 'birthday', '') ELSE contacts.birthday END")
    expect(saveStabilityMigration).not.toContain("birthday = CASE WHEN _contact_patch ? 'birthday' THEN nullif(_contact_patch ->> 'birthday', '')::date")
    expect(saveStabilityMigration).toContain("cadence_override = CASE WHEN _contact_patch ? 'cadence_override' THEN nullif(_contact_patch ->> 'cadence_override', '')::public.cadence ELSE contacts.cadence_override END")
    expect(saveStabilityMigration).toContain("global_region = CASE WHEN _contact_patch ? 'global_region' THEN nullif(_contact_patch ->> 'global_region', '')::public.global_region ELSE contacts.global_region END")
    expect(saveStabilityMigration).toContain("gender = CASE WHEN _contact_patch ? 'gender' THEN nullif(_contact_patch ->> 'gender', '')::public.gender_type ELSE contacts.gender END")
    expect(saveStabilityMigration).toContain("contact_frequency = CASE WHEN _contact_patch ? 'contact_frequency' THEN nullif(_contact_patch ->> 'contact_frequency', '')::public.contact_frequency ELSE contacts.contact_frequency END")
    expect(saveStabilityMigration).toContain("type = CASE WHEN _contact_patch ? 'type' THEN coalesce(nullif(_contact_patch ->> 'type', '')::public.relationship_type, contacts.type) ELSE contacts.type END")
    expect(saveStabilityMigration).toContain("status = CASE WHEN _contact_patch ? 'status' THEN coalesce(nullif(_contact_patch ->> 'status', '')::public.relationship_status, contacts.status) ELSE contacts.status END")
    expect(saveStabilityMigration).not.toContain('FROM public.get_shared_contacts_with_me() AS incoming')
  })
})
