// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_PROJECT_ID = import.meta.env.VITE_SUPABASE_PROJECT_ID;
const CANONICAL_SUPABASE_PROJECT_ID = 'zsecxtxpwmvgggqksdfb';

function validateSupabaseConfig() {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error('Supabase environment variables are missing.');
  }

  const projectFromUrl = new URL(SUPABASE_URL).hostname.split('.')[0];
  const refs = [projectFromUrl, SUPABASE_PROJECT_ID].filter(Boolean);
  const nonCanonicalRefs = refs.filter(ref => ref !== CANONICAL_SUPABASE_PROJECT_ID);

  if (nonCanonicalRefs.length > 0) {
    throw new Error('Supabase configuration is not using the canonical production project.');
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

validateSupabaseConfig();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
